### ISSUE TITLE
Template lint errors not getting output in terminal

### ISSUE THREAD

**Issue by Ornhoj** [vuejs/vue-eslint-parser#159]
I've created at project with vite + vue-ts and added eslint, typescript and prettier to handling formatting and code styling.

Everything works as expected except I'm not getting any html template error outputs, in my terminal when running my lint.

**Reproductional repo:**
https://github.com/Ornhoj/vite-eslint-issue

**What happens**
HTML template errors not getting to terminal

**What I expect**
HTML template errors getting to terminal

**Comment by ota-meshi** [comment]
I don't know what you're having trouble with, but your problem shouldn't be a parser problem.
In the first place, I cannot run eslint because the eslint configuration is not configured correctly in your repository.

If you still have problems after configuring the eslint configuration correctly, use the issue template in the eslint-plugin-vue repository to open the issue.

https://github.com/vuejs/eslint-plugin-vue/issues/new?template=bug_report.md
